<a href="https://colab.research.google.com/github/wldnjd2/Python/blob/main/21_11_02_python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

라이브러리 불러오기

In [11]:
import numpy as np
print (np.__version__)

1.19.5


테스트

In [6]:
#배열 생성
temp = np.array([1, 2, 3])
print(type(temp))

<class 'numpy.ndarray'>


Numpy 배열 생성 및 둘러보기

In [8]:
data1 = [1,2,3]     #python list를 이용함
data1

[1, 1, 2, 2, 3, 4]

In [9]:
data2 = [1,1,2,2,3,4]
data2

[1, 1, 2, 2, 3, 4]

In [12]:
my_array1 = np.array(data1)   #numpy를 이용하여 array 정의
print(my_array1)
print(my_array1.shape)    #my_array1의 형태를 확인

[1 2 3]
(3,)


In [14]:
my_array2 = np.array(data2)
print(my_array2)
print(my_array2.shape)

[1 1 2 2 3 4]
(6,)


In [15]:
my_array3 = np.array([3,6,9,12])
print(my_array3)
print(my_array3.shape)
print(my_array3.dtype)    #my_array3의 데이터타입 확인

[ 3  6  9 12]
(4,)
int64


In [18]:
my_array4 = np.array([[2,4,6,],[8,10,12],[14,16,18],[20,22,24]])
print(my_array4)
print(my_array4.shape)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
(4, 3)


In [21]:
my_array5 = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print(my_array5)
my_array5.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

Numpy 기본 함수들

arange 메소드

In [22]:
arrange_array = np.arange(5)      #0부터 4까지 정수값 반환
arrange_array

array([0, 1, 2, 3, 4])

In [25]:
arrange_array3 = np.arange(1,9)   #1부터 9까지 정수값 반환
arrange_array3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
arrange_array2 = np.arange(1,9,3)   #1부터 8까지 3씩 띄어서 정수값 반환
arrange_array2

array([1, 4, 7])

zeroes, ones 메소드

In [27]:
zeros_array = np.zeros((3,2))
print(zeros_array)
print("Data Type is: ", zeros_array.dtype)      #실수형이라서 0뒤에 .이 붙음
print("Data Shape is: ", zeros_array.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
Data Type is:  float64
Data Shape is:  (3, 2)


In [28]:
ones_array = np.ones((3,4), dtype='int32')
print(ones_array)
print("Data Type is: ", ones_array.dtype)
print("Data Shape is: ", ones_array.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Data Type is:  int32
Data Shape is:  (3, 4)


reshape

In [29]:
after_reshape = ones_array.reshape(6,2)
print(after_reshape)
print("Data Shape is: ", after_reshape.shape)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
Data Shape is:  (6, 2)


In [31]:
after_reshape = ones_array.reshape(5,3)     #크기가 15랑 12랑 안맞아서 Error
after_reshape

ValueError: ignored

In [32]:
#3차원 배열도 가능
# 3 x 4 = 12 --> 2 x 3 x 2 =12
after_reshape = ones_array.reshape(2,3,2)
print(after_reshape)
print("Data Shape is: ", after_reshape.shape)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
Data Shape is:  (2, 3, 2)


In [38]:
after_reshape2 = ones_array.reshape(-1,6)
print("reshape(-1,6)?", after_reshape2.shape)
print(after_reshape2)

reshape(-1,6)? (2, 6)
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [36]:
after_reshape3 = ones_array.reshape(3,-1)
print("reshape(3,-1)?",after_reshape3.shape)
print(after_reshape3)
print("Data Shape is: ",after_reshape3.shape)

reshape(3,-1)?
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Data Shape is:  (3, 4)


Numpy 인덱싱과 슬라이딩

In [39]:
my_array = np.arange(start=0, stop=4)
print(my_array)

[0 1 2 3]


In [40]:
print("my_array의 1번째 요소, 즉 위치값이 0인 것은: ", my_array[0])

my_array의 1번째 요소, 즉 위치값이 0인 것은:  0


In [41]:
my_array2 = np.arange(start=3,stop=30,step=3)
my_array2 = my_array2.reshape(3,3)
my_array2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [42]:
my_array2[0:2,0:2]

array([[ 3,  6],
       [12, 15]])

In [43]:
my_array2[1:3,:]

array([[12, 15, 18],
       [21, 24, 27]])

In [44]:
my_array2[:,:]

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

Numpy 정렬

sort()

In [46]:
height_arr = np.array([174,165,180,182,168])
sorted_height_arr = np.sort(height_arr)

print('정렬 전: ',height_arr)
print('키가 작은 순으로 정렬: ',sorted_height_arr)

정렬 전:  [174 165 180 182 168]
키 큰 순으로 정렬 후:  [165 168 174 180 182]


In [49]:
#[::-1]
desc_sorted_height_arr = np.sort(height_arr)[::-1]
print('키가 큰 순으로 정렬: ' ,desc_sorted_height_arr)

키가 큰 순으로 정렬:  [182 180 174 168 165]


argsort()

In [52]:
fives = np.array([10,5,15,20])
fives_order = fives.argsort()
print(fives)
print(fives_order)
print(fives[fives_order])

[10  5 15 20]
[1 0 2 3]
[ 5 10 15 20]
